/**
 * GitHub API Client
 *
 * Wrapper directo de fetch para los endpoints REST de GitHub que usamos.
 * No uso @octokit/rest porque agrega ~500KB y nuestro uso es acotado.
 *
 * Documentación: https://docs.github.com/en/rest
 *
 * Endpoints usados:
 *   GET    /user                          Info del user
 *   GET    /user/repos                    Listar repos del user
 *   POST   /user/repos                    Crear repo (personal)
 *   POST   /orgs/{org}/repos              Crear repo en org
 *   GET    /repos/{owner}/{repo}          Info de un repo
 *   GET    /repos/{owner}/{repo}/branches/{branch}    Info de un branch
 *   GET    /repos/{owner}/{repo}/git/trees/{sha}      Tree (lista de archivos)
 *   POST   /repos/{owner}/{repo}/git/blobs            Crear blob (archivo)
 *   POST   /repos/{owner}/{repo}/git/trees            Crear tree
 *   POST   /repos/{owner}/{repo}/git/commits          Crear commit
 *   PATCH  /repos/{owner}/{repo}/git/refs/heads/{br}  Actualizar branch
 */

const BASE_URL = 'https://api.github.com'
const USER_AGENT = 'Achilltest'

/**
 * Wrapper para fetch a la API de GitHub.
 * Maneja errores y rate limiting.
 *
 * @returns {Promise<any>} Body parseado como JSON
 * @throws {Error} si HTTP no es 2xx
 */
async function ghFetch(path, options = {}) {
  const url = path.startsWith('http') ? path : `${BASE_URL}${path}`

  const headers = {
    'Accept':              'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent':          USER_AGENT,
    'Authorization':       options.token ? `Bearer ${options.token}` : undefined,
    ...(options.body && typeof options.body === 'string'
      ? { 'Content-Type': 'application/json' }
      : {}),
    ...(options.headers || {}),
  }

  // Limpiar undefined
  for (const k of Object.keys(headers)) {
    if (headers[k] === undefined) delete headers[k]
  }

  const res = await fetch(url, {
    method:  options.method || 'GET',
    headers,
    body:    options.body,
  })

  // Rate limit info
  const remaining = res.headers.get('x-ratelimit-remaining')
  if (remaining !== null && parseInt(remaining) < 10) {
    console.warn(`[GitHub] Rate limit bajo: ${remaining} requests restantes`)
  }

  if (!res.ok) {
    let errorBody = null
    try { errorBody = await res.json() } catch {}
    const message = errorBody?.message || `HTTP ${res.status}`
    const err = new Error(`GitHub: ${message}`)
    err.status = res.status
    err.response = errorBody
    throw err
  }

  // 204 No Content
  if (res.status === 204) return null
  return res.json()
}

// ── ENDPOINTS USADOS ────────────────────────────────────────────────────────

/**
 * Obtiene info del user autenticado.
 */
export async function getAuthenticatedUser(token) {
  return ghFetch('/user', { token })
}

/**
 * Lista los repos del user autenticado.
 *
 * @param {object} opts
 * @param {string} [opts.type=all]  all | owner | public | private | member
 * @param {string} [opts.sort=updated]
 * @param {number} [opts.perPage=30]
 */
export async function listUserRepos(token, opts = {}) {
  const params = new URLSearchParams({
    type:      opts.type      || 'owner',
    sort:      opts.sort      || 'updated',
    per_page:  String(opts.perPage || 30),
    page:      String(opts.page    || 1),
  })
  return ghFetch(`/user/repos?${params}`, { token })
}

/**
 * Lista las organizaciones del user.
 */
export async function listUserOrgs(token) {
  return ghFetch('/user/orgs', { token })
}

/**
 * Verifica si un repo existe para el dueño del token.
 */
export async function repoExists(token, owner, repo) {
  try {
    await ghFetch(`/repos/${owner}/${repo}`, { token })
    return true
  } catch (err) {
    if (err.status === 404) return false
    throw err
  }
}

/**
 * Crea un repo.
 *
 * @param {object} opts
 * @param {string} opts.name          Nombre del repo
 * @param {string} [opts.description]
 * @param {boolean} [opts.private=true]
 * @param {string} [opts.org]         Si se provee, crea bajo la org
 * @param {boolean} [opts.autoInit=true]  Si crear con README (necesario para tener una branch)
 */
export async function createRepo(token, opts) {
  const path = opts.org ? `/orgs/${opts.org}/repos` : '/user/repos'
  const body = {
    name:        opts.name,
    description: opts.description || 'Generated by Achilltest',
    private:     opts.private !== false,
    auto_init:   opts.autoInit !== false,
    has_issues:  true,
    has_wiki:    false,
  }
  return ghFetch(path, {
    token,
    method: 'POST',
    body:   JSON.stringify(body),
  })
}

/**
 * Obtiene info de un branch (incluye el SHA del último commit).
 */
export async function getBranch(token, owner, repo, branch) {
  return ghFetch(`/repos/${owner}/${repo}/branches/${branch}`, { token })
}

/**
 * Crea un blob (archivo) en el repo. Devuelve el SHA del blob.
 */
export async function createBlob(token, owner, repo, content, encoding = 'utf-8') {
  const body = {
    content,
    encoding,   // utf-8 | base64
  }
  const result = await ghFetch(`/repos/${owner}/${repo}/git/blobs`, {
    token,
    method: 'POST',
    body:   JSON.stringify(body),
  })
  return result.sha
}

/**
 * Crea un tree (estructura de archivos). Si baseTree se provee, el nuevo tree
 * extiende el existente (útil para no perder archivos no modificados).
 */
export async function createTree(token, owner, repo, tree, baseTree = null) {
  const body = {
    tree,             // [{ path, mode: '100644', type: 'blob', sha }]
    ...(baseTree ? { base_tree: baseTree } : {}),
  }
  return ghFetch(`/repos/${owner}/${repo}/git/trees`, {
    token,
    method: 'POST',
    body:   JSON.stringify(body),
  })
}

/**
 * Crea un commit apuntando al tree dado.
 */
export async function createCommit(token, owner, repo, message, treeSha, parentShas) {
  const body = {
    message,
    tree:    treeSha,
    parents: Array.isArray(parentShas) ? parentShas : [parentShas],
  }
  return ghFetch(`/repos/${owner}/${repo}/git/commits`, {
    token,
    method: 'POST',
    body:   JSON.stringify(body),
  })
}

/**
 * Actualiza la referencia de un branch para apuntar al commit dado.
 */
export async function updateRef(token, owner, repo, branch, commitSha, force = false) {
  const body = {
    sha:   commitSha,
    force,
  }
  return ghFetch(`/repos/${owner}/${repo}/git/refs/heads/${branch}`, {
    token,
    method: 'PATCH',
    body:   JSON.stringify(body),
  })
}

/**
 * Lista los archivos de un tree (recursivo).
 */
export async function getTree(token, owner, repo, treeSha, recursive = true) {
  const params = recursive ? '?recursive=1' : ''
  return ghFetch(`/repos/${owner}/${repo}/git/trees/${treeSha}${params}`, { token })
}
